### ISSUE TITLE
Gear icon with long employer name

### ISSUE THREAD

**Issue by johnnyoshika** [bcjobs/assets#47]
Gear icon drops and collides with other elements with long employer names in jobcentre:

![image](https://user-images.githubusercontent.com/504505/35844691-90f4a8ec-0ac3-11e8-96dc-a0da83ab7dd3.png)

It doesn't seem to happen with cpajobs:

![image](https://user-images.githubusercontent.com/504505/35844699-9aab951c-0ac3-11e8-8f64-554ea720d389.png)

**Comment by reizelfranz** [comment]
@johnnyoshika I have updated this in the jobcentre-fixes-2 branch
