### ISSUE TITLE
Add stripe-element styling

### ISSUE THREAD

**Issue by johnnyoshika** [bcjobs/assets#56]
We're going to change our integration with Stripe, which requires us to style some div elements as if they were input elements. Can you please add these styles to the correct less files?

Please add them to the `stripe-elements` branch.

## Jobcentre (including bctechjobs);
```
.stripe-element {
    border: 0;
    padding: 12px 15px;
    height: 40px;
    border-radius: 5px;
    color: #414141;
    background: #EBEBEB;
    box-shadow: none;
}
.stripe-element-focus {
    box-shadow: 2px 1.464px 4px 0px rgba(0, 0, 0, 0.21);
}
.stripe-element-invalid {
    border: 1px solid #BBBBBB;
    border-bottom: 5px solid #fcc;
}
```

## CPA Jobs
```
.stripe-element {
    background: #f7f7f7;
    border: 0 none;
    border-radius: 5px;
    height: 40px;
    padding: 12px 15px;
}
```

## Admin for all sites, including jobcentre, bctechjobs, and cpajobs
```
.stripe-element {
    padding: 4px 6px;
    border: 1px solid #BBBBBB;
}
/* mimic webkit's default focus ring */
.stripe-element-focus {
    outline-offset: -2px;
    outline: -webkit-focus-ring-color auto 5px;
}
```

**Comment by reizelfranz** [comment]
@johnnyoshika I have added these: https://github.com/bcjobs/assets/pull/57

**Comment by johnnyoshika** [comment]
@reizelfranz Unfortunately there is a mistake. If you have a look at the generated CSS, it has the admin classes in non-admin CSS:

Example:

https://github.com/bcjobs/assets/pull/57/commits/4c1477d06d150b3e3c79e559120f1ce3f3b98294#diff-874d3571597f870362f66b951cc98e3b

If you move this: https://github.com/bcjobs/assets/pull/57/commits/4c1477d06d150b3e3c79e559120f1ce3f3b98294#diff-2cbdcb2b8f328fac432fa355fa3291c0

...to _admin.less, that should fix the issue.
